### PR TITLE
increased chef-client version and migrated tests to inspec

### PR DESCRIPTION
**Pull request by goblin23**
Increased chef-client version to be compatible with current versions of the ohai cookbook.
Moved to [inspec](https://www.chef.io/inspec/) as verifier since the current version of the chefdk moved to inspec as a default.

### CODE REVIEW

**Comment by EtienneK** [comment]
You're doing a lot of hard work. Thanks!

Will review and merge once I see you've settled down a bit.

**Comment by goblin23** [comment]
if you want to review my changes you can do so now. My fork already runs in our production system

**Comment by EtienneK** [comment]
@goblin23  I don't use this cookbook anymore. Maybe we should make your fork the official one. You up for that?

**Comment by goblin23** [comment]
Yes i would be up for that

**Comment by EtienneK** [comment]
Before I can transfer it, you will need to rename / remove your fork of this repo.

**Comment by goblin23** [comment]
Ok i removed the repo from my account

**Comment by goblin23** [comment]
Can you try transferring the repo ?

**Comment by EtienneK** [comment]
I did request a transfer. You must accept it.

**Comment by goblin23** [comment]
Sorry I did not receive the request because I cannot access my primary email anymore. I changed my primary email now. Is it possible to resend the request ? Sorry for the inconvenience.

**Comment by EtienneK** [comment]
Ok I have requested the transfer again.

**Pull request merged**
